version: '3.8'

services:
  controller:
    container_name: ml-analysis-provider-controller
    build: 
      context: ./controller/
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - 8080:8080
    restart: always
  worker:
    container_name: ml-analysis-provider-worker
    build: 
      context: ./worker/
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    restart: always
  worker-1:
    container_name: ml-analysis-provider-worker-1
    build: 
      context: ./worker/
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./worker:/app
    restart: always
  nats:
    container_name: ml-analysis-provider-nats
    image: nats:2.10
    restart: always
    ports:
      - 8222:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
  nats-1:
    container_name: ml-analysis-provider-nats-1
    image: nats:2.10
    restart: always
    depends_on:
      - nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  elasticsearch:
    container_name: ml-analysis-provider-elasticsearch
    image: elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  logstash:
    container_name: ml-analysis-provider-logstash
    image: logstash:8.5.1
    ports:
      - 5000:5000
    restart: always
    environment:
      - CONFIG_SUPPORT_ESCAPE=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - logstashdata:/usr/share/logstash/data
      - ./elk/logstash.local.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/postgres-jdbc-42.7.4.jar:/usr/share/logstash/logstash-core/lib/jars/postgres-jdbc-42.7.4.jar
  kibana:
   container_name: ml-analysis-provider-kibana
   depends_on:
    - elasticsearch
   image: kibana:8.5.1
   restart: always
   labels:
     co.elastic.logs/module: kibana
   volumes:
     - kibanadata:/usr/share/kibana/data
   ports:
     - 5601:5601
   environment:
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  postgres:
    container_name: ml-analysis-provider-postgres
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_DB=ml_analysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgresdata:
  elasticdata:
  logstashdata:
  kibanadata: