version: '3.8'

services:
  controller:
    container_name: ml-analysis-provider-controller
    build: ./backend/
    volumes:
      - ./controller:/app
    ports:
      - 8080:8080
    restart: always
  worker:
    container_name: ml-analysis-provider-worker
    build: ./worker/
    volumes:
      - ./worker:/app
    restart: always
  # worker-1:
  #   container_name: ml-analysis-provider-worker-1
  #   build: ./worker/
  #   volumes:
  #     - ./worker:/app
  #   restart: always
  nats:
    container_name: ml-analysis-provider-nats
    image: nats:2.10
    restart: always
    ports:
      - 8222:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
  nats-1:
    container_name: ml-analysis-provider-nats-1
    image: nats:2.10
    restart: always
    depends_on:
      - nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"