nats:
  conn_string: nats://localhost:4222
elasticsearch:
  addrs:
    - http://localhost:9200
postgres:
  conn_string: postgres://postgres:postgres_pass@localhost:5432/ml_analysis?&pool_max_conns=10 