esJavaOpts: "-Xmx128m -Xms128m"
image: elasticsearch
imageTag: 8.5.1
antiAffinity: soft
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M